[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = ["TMee3  <theopsna@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.4"
pillow = "^10.0.0"
flake8 = "^6.1.0"
flake8-html = "^0.4.3"
djangorestframework = "^3.14.0"
djangorestframework-simplejwt = "^5.2.2"
django-rest-framework-nested = "^0.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
