# Generated by Django 4.2.5 on 2023-09-05 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consent",
            old_name="date",
            new_name="date_given",
        ),
    ]
