# Generated by Django 4.1.7 on 2023-04-06 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(related_name='contributor_project', through='project.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
