# Generated by Django 4.2.5 on 2023-09-17 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "API_IssueTrackingSystem",
            "0007_rename_user_issue_assigned_to_comment_updated_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_be_contacted", models.BooleanField(default=False)),
                ("can_data_be_shared", models.BooleanField(default=False)),
                ("birth_date", models.DateField(default=None)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
