# Generated by Django 4.2.5 on 2023-09-17 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API_IssueTrackingSystem", "0008_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="birth_date",
        ),
    ]
