# Generated by Django 4.2.5 on 2023-09-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_IssueTrackingSystem", "0009_remove_userprofile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
