# Generated by Django 4.2.5 on 2023-09-26 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("API_IssueTrackingSystem", "0010_userprofile_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("en attente", "en attente"),
                    ("en cours", "en cours"),
                    ("terminé", "terminé"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
